CREATE TABLE RUTES ( num_r INTEGER PRIMARY KEY AUTO_INCREMENT, nom_r TEXT, desn INTEGER, desn_acum INTEGER );
INSERT INTO RUTES VALUES(1,'Pujada a Penyagolosa',530,530);
INSERT INTO RUTES VALUES(2,'La Magdalena',51,84);
INSERT INTO RUTES VALUES(3,'Pelegrins de Les Useres',896,1738);

